<?php
/**
 * Currency data: ISO 4217 codes, Spanish names, and symbols.
 * Used throughout the app for display and selection.
 */

if (!function_exists('get_currency_list')) {
    function get_currency_list(): array {
        return [
            ['code' => 'AED', 'name' => 'Dírham de los Emiratos', 'symbol' => 'د.إ'],
            ['code' => 'AFN', 'name' => 'Afgani afgano', 'symbol' => '؋'],
            ['code' => 'ALL', 'name' => 'Lek albanés', 'symbol' => 'L'],
            ['code' => 'AMD', 'name' => 'Dram armenio', 'symbol' => '֏'],
            ['code' => 'ANG', 'name' => 'Florín antillano neerlandés', 'symbol' => 'ƒ'],
            ['code' => 'AOA', 'name' => 'Kwanza angoleño', 'symbol' => 'Kz'],
            ['code' => 'ARS', 'name' => 'Peso argentino', 'symbol' => '$'],
            ['code' => 'AUD', 'name' => 'Dólar australiano', 'symbol' => '$'],
            ['code' => 'AWG', 'name' => 'Florín arubeño', 'symbol' => 'ƒ'],
            ['code' => 'AZN', 'name' => 'Manat azerbaiyano', 'symbol' => '₼'],
            ['code' => 'BAM', 'name' => 'Marco convertible de Bosnia', 'symbol' => 'KM'],
            ['code' => 'BBD', 'name' => 'Dólar de Barbados', 'symbol' => '$'],
            ['code' => 'BDT', 'name' => 'Taka bangladesí', 'symbol' => '৳'],
            ['code' => 'BGN', 'name' => 'Lev búlgaro', 'symbol' => 'лв'],
            ['code' => 'BHD', 'name' => 'Dinar bareiní', 'symbol' => 'BD'],
            ['code' => 'BIF', 'name' => 'Franco burundés', 'symbol' => 'Fr'],
            ['code' => 'BMD', 'name' => 'Dólar de Bermudas', 'symbol' => '$'],
            ['code' => 'BND', 'name' => 'Dólar de Brunéi', 'symbol' => '$'],
            ['code' => 'BOB', 'name' => 'Boliviano', 'symbol' => 'Bs.'],
            ['code' => 'BRL', 'name' => 'Real brasileño', 'symbol' => 'R$'],
            ['code' => 'BSD', 'name' => 'Dólar bahameño', 'symbol' => '$'],
            ['code' => 'BTN', 'name' => 'Ngultrum butanés', 'symbol' => 'Nu'],
            ['code' => 'BWP', 'name' => 'Pula botsuanesa', 'symbol' => 'P'],
            ['code' => 'BYN', 'name' => 'Rublo bielorruso', 'symbol' => 'Br'],
            ['code' => 'BZD', 'name' => 'Dólar de Belice', 'symbol' => 'BZ$'],
            ['code' => 'CAD', 'name' => 'Dólar canadiense', 'symbol' => '$'],
            ['code' => 'CDF', 'name' => 'Franco congoleño', 'symbol' => 'Fr'],
            ['code' => 'CHF', 'name' => 'Franco suizo', 'symbol' => 'Fr'],
            ['code' => 'CLP', 'name' => 'Peso chileno', 'symbol' => '$'],
            ['code' => 'CNY', 'name' => 'Yuan chino', 'symbol' => '¥'],
            ['code' => 'COP', 'name' => 'Peso colombiano', 'symbol' => '$'],
            ['code' => 'CRC', 'name' => 'Colón costarricense', 'symbol' => '₡'],
            ['code' => 'CUC', 'name' => 'Peso cubano convertible', 'symbol' => '$'],
            ['code' => 'CUP', 'name' => 'Peso cubano', 'symbol' => '$'],
            ['code' => 'CVE', 'name' => 'Escudo caboverdiano', 'symbol' => '$'],
            ['code' => 'CZK', 'name' => 'Corona checa', 'symbol' => 'Kč'],
            ['code' => 'DJF', 'name' => 'Franco yibutiano', 'symbol' => 'Fr'],
            ['code' => 'DKK', 'name' => 'Corona danesa', 'symbol' => 'kr'],
            ['code' => 'DOP', 'name' => 'Peso dominicano', 'symbol' => '$'],
            ['code' => 'DZD', 'name' => 'Dinar argelino', 'symbol' => 'دج'],
            ['code' => 'EGP', 'name' => 'Libra egipcia', 'symbol' => '£'],
            ['code' => 'ERN', 'name' => 'Nakfa eritreo', 'symbol' => 'Nfk'],
            ['code' => 'ETB', 'name' => 'Birr etíope', 'symbol' => 'Br'],
            ['code' => 'EUR', 'name' => 'Euro', 'symbol' => '€'],
            ['code' => 'FJD', 'name' => 'Dólar fiyiano', 'symbol' => '$'],
            ['code' => 'FKP', 'name' => 'Libra malvinense', 'symbol' => '£'],
            ['code' => 'GBP', 'name' => 'Libra esterlina', 'symbol' => '£'],
            ['code' => 'GEL', 'name' => 'Lari georgiano', 'symbol' => '₾'],
            ['code' => 'GHS', 'name' => 'Cedi ghanés', 'symbol' => '₵'],
            ['code' => 'GIP', 'name' => 'Libra gibraltareña', 'symbol' => '£'],
            ['code' => 'GMD', 'name' => 'Dalasi gambiano', 'symbol' => 'D'],
            ['code' => 'GNF', 'name' => 'Franco guineano', 'symbol' => 'Fr'],
            ['code' => 'GTQ', 'name' => 'Quetzal guatemalteco', 'symbol' => 'Q'],
            ['code' => 'GYD', 'name' => 'Dólar guyanés', 'symbol' => '$'],
            ['code' => 'HKD', 'name' => 'Dólar de Hong Kong', 'symbol' => '$'],
            ['code' => 'HNL', 'name' => 'Lempira hondureño', 'symbol' => 'L'],
            ['code' => 'HRK', 'name' => 'Kuna croata', 'symbol' => 'kn'],
            ['code' => 'HTG', 'name' => 'Gourde haitiano', 'symbol' => 'G'],
            ['code' => 'HUF', 'name' => 'Forinto húngaro', 'symbol' => 'Ft'],
            ['code' => 'IDR', 'name' => 'Rupia indonesia', 'symbol' => 'Rp'],
            ['code' => 'ILS', 'name' => 'Séquel israelí', 'symbol' => '₪'],
            ['code' => 'INR', 'name' => 'Rupia india', 'symbol' => '₹'],
            ['code' => 'IQD', 'name' => 'Dinar iraquí', 'symbol' => 'ع.د'],
            ['code' => 'IRR', 'name' => 'Rial iraní', 'symbol' => '﷼'],
            ['code' => 'ISK', 'name' => 'Corona islandesa', 'symbol' => 'kr'],
            ['code' => 'JMD', 'name' => 'Dólar jamaicano', 'symbol' => 'J$'],
            ['code' => 'JOD', 'name' => 'Dinar jordano', 'symbol' => 'JD'],
            ['code' => 'JPY', 'name' => 'Yen japonés', 'symbol' => '¥'],
            ['code' => 'KES', 'name' => 'Chelín keniano', 'symbol' => 'KSh'],
            ['code' => 'KGS', 'name' => 'Som kirguís', 'symbol' => 'с'],
            ['code' => 'KHR', 'name' => 'Riel camboyano', 'symbol' => '៛'],
            ['code' => 'KMF', 'name' => 'Franco comorense', 'symbol' => 'Fr'],
            ['code' => 'KPW', 'name' => 'Won norcoreano', 'symbol' => '₩'],
            ['code' => 'KRW', 'name' => 'Won surcoreano', 'symbol' => '₩'],
            ['code' => 'KWD', 'name' => 'Dinar kuwaití', 'symbol' => 'KD'],
            ['code' => 'KYD', 'name' => 'Dólar de las Islas Caimán', 'symbol' => '$'],
            ['code' => 'KZT', 'name' => 'Tenge kazajo', 'symbol' => '₸'],
            ['code' => 'LAK', 'name' => 'Kip laosiano', 'symbol' => '₭'],
            ['code' => 'LBP', 'name' => 'Libra libanesa', 'symbol' => 'LL'],
            ['code' => 'LKR', 'name' => 'Rupia de Sri Lanka', 'symbol' => '₨'],
            ['code' => 'LRD', 'name' => 'Dólar liberiano', 'symbol' => '$'],
            ['code' => 'LSL', 'name' => 'Loti lesotense', 'symbol' => 'L'],
            ['code' => 'LYD', 'name' => 'Dinar libio', 'symbol' => 'LD'],
            ['code' => 'MAD', 'name' => 'Dírham marroquí', 'symbol' => 'MAD'],
            ['code' => 'MDL', 'name' => 'Leu moldavo', 'symbol' => 'L'],
            ['code' => 'MGA', 'name' => 'Ariary malgache', 'symbol' => 'Ar'],
            ['code' => 'MKD', 'name' => 'Denar macedonio', 'symbol' => 'ден'],
            ['code' => 'MMK', 'name' => 'Kyat de Myanmar', 'symbol' => 'K'],
            ['code' => 'MNT', 'name' => 'Tugrik mongol', 'symbol' => '₮'],
            ['code' => 'MOP', 'name' => 'Pataca macaense', 'symbol' => 'P'],
            ['code' => 'MRO', 'name' => 'Uguiya mauritana', 'symbol' => 'UM'],
            ['code' => 'MUR', 'name' => 'Rupia mauriciana', 'symbol' => '₨'],
            ['code' => 'MVR', 'name' => 'Rufiyaa maldiva', 'symbol' => 'Rf'],
            ['code' => 'MWK', 'name' => 'Kwacha malauí', 'symbol' => 'MK'],
            ['code' => 'MXN', 'name' => 'Peso mexicano', 'symbol' => '$'],
            ['code' => 'MYR', 'name' => 'Ringgit malayo', 'symbol' => 'RM'],
            ['code' => 'MZN', 'name' => 'Metical mozambiqueño', 'symbol' => 'MT'],
            ['code' => 'NAD', 'name' => 'Dólar namibio', 'symbol' => '$'],
            ['code' => 'NGN', 'name' => 'Naira nigeriana', 'symbol' => '₦'],
            ['code' => 'NIO', 'name' => 'Córdoba nicaragüense', 'symbol' => 'C$'],
            ['code' => 'NOK', 'name' => 'Corona noruega', 'symbol' => 'kr'],
            ['code' => 'NPR', 'name' => 'Rupia nepalesa', 'symbol' => '₨'],
            ['code' => 'NZD', 'name' => 'Dólar neozelandés', 'symbol' => '$'],
            ['code' => 'OMR', 'name' => 'Rial omaní', 'symbol' => '﷼'],
            ['code' => 'PAB', 'name' => 'Balboa panameño', 'symbol' => 'B/.'],
            ['code' => 'PEN', 'name' => 'Sol peruano', 'symbol' => 'S/.'],
            ['code' => 'PGK', 'name' => 'Kina de Papúa Nueva Guinea', 'symbol' => 'K'],
            ['code' => 'PHP', 'name' => 'Peso filipino', 'symbol' => '₱'],
            ['code' => 'PKR', 'name' => 'Rupia pakistaní', 'symbol' => '₨'],
            ['code' => 'PLN', 'name' => 'Esloti polaco', 'symbol' => 'zł'],
            ['code' => 'PYG', 'name' => 'Guaraní paraguayo', 'symbol' => '₲'],
            ['code' => 'QAR', 'name' => 'Rial catarí', 'symbol' => '﷼'],
            ['code' => 'RON', 'name' => 'Leu rumano', 'symbol' => 'lei'],
            ['code' => 'RSD', 'name' => 'Dinar serbio', 'symbol' => 'din'],
            ['code' => 'RUB', 'name' => 'Rublo ruso', 'symbol' => '₽'],
            ['code' => 'RWF', 'name' => 'Franco ruandés', 'symbol' => 'Fr'],
            ['code' => 'SAR', 'name' => 'Riyal saudí', 'symbol' => '﷼'],
            ['code' => 'SBD', 'name' => 'Dólar de las Islas Salomón', 'symbol' => '$'],
            ['code' => 'SCR', 'name' => 'Rupia de Seychelles', 'symbol' => '₨'],
            ['code' => 'SDG', 'name' => 'Libra sudanesa', 'symbol' => 'ج.س.'],
            ['code' => 'SEK', 'name' => 'Corona sueca', 'symbol' => 'kr'],
            ['code' => 'SGD', 'name' => 'Dólar de Singapur', 'symbol' => '$'],
            ['code' => 'SHP', 'name' => 'Libra de Santa Elena', 'symbol' => '£'],
            ['code' => 'SLL', 'name' => 'Leone de Sierra Leona', 'symbol' => 'Le'],
            ['code' => 'SOS', 'name' => 'Chelín somalí', 'symbol' => 'Sh'],
            ['code' => 'SRD', 'name' => 'Dólar surinamés', 'symbol' => '$'],
            ['code' => 'STD', 'name' => 'Dobra de Santo Tomé y Príncipe', 'symbol' => 'Db'],
            ['code' => 'SVC', 'name' => 'Colón salvadoreño', 'symbol' => '₡'],
            ['code' => 'SYP', 'name' => 'Libra siria', 'symbol' => '£'],
            ['code' => 'SZL', 'name' => 'Lilangeni suazi', 'symbol' => 'L'],
            ['code' => 'THB', 'name' => 'Baht tailandés', 'symbol' => '฿'],
            ['code' => 'TJS', 'name' => 'Somoni tayiko', 'symbol' => 'SM'],
            ['code' => 'TMT', 'name' => 'Manat turcomano', 'symbol' => 'T'],
            ['code' => 'TND', 'name' => 'Dinar tunecino', 'symbol' => 'د.ت'],
            ['code' => 'TOP', 'name' => 'Paʻanga tongano', 'symbol' => 'T$'],
            ['code' => 'TRY', 'name' => 'Lira turca', 'symbol' => '₺'],
            ['code' => 'TTD', 'name' => 'Dólar de Trinidad y Tobago', 'symbol' => 'TT$'],
            ['code' => 'TWD', 'name' => 'Nuevo dólar taiwanés', 'symbol' => 'NT$'],
            ['code' => 'TZS', 'name' => 'Chelín tanzano', 'symbol' => 'Sh'],
            ['code' => 'UAH', 'name' => 'Grivna ucraniana', 'symbol' => '₴'],
            ['code' => 'UGX', 'name' => 'Chelín ugandés', 'symbol' => 'Sh'],
            ['code' => 'USD', 'name' => 'Dólar estadounidense', 'symbol' => '$'],
            ['code' => 'UYU', 'name' => 'Peso uruguayo', 'symbol' => '$U'],
            ['code' => 'UZS', 'name' => 'Sum uzbeko', 'symbol' => 'лв'],
            ['code' => 'VEF', 'name' => 'Bolívar venezolano', 'symbol' => 'Bs.F'],
            ['code' => 'VND', 'name' => 'Dong vietnamita', 'symbol' => '₫'],
            ['code' => 'VUV', 'name' => 'Vatu vanuatense', 'symbol' => 'Vt'],
            ['code' => 'WST', 'name' => 'Tālā samoano', 'symbol' => 'T'],
            ['code' => 'XAF', 'name' => 'Franco CFA de África Central', 'symbol' => 'Fr'],
            ['code' => 'XCD', 'name' => 'Dólar del Caribe Oriental', 'symbol' => '$'],
            ['code' => 'XOF', 'name' => 'Franco CFA de África Occidental', 'symbol' => 'Fr'],
            ['code' => 'XPF', 'name' => 'Franco CFP', 'symbol' => 'Fr'],
            ['code' => 'YER', 'name' => 'Rial yemení', 'symbol' => '﷼'],
            ['code' => 'ZAR', 'name' => 'Rand sudafricano', 'symbol' => 'R'],
            ['code' => 'ZMW', 'name' => 'Kwacha zambiano', 'symbol' => 'ZK'],
            ['code' => 'ZWL', 'name' => 'Dólar zimbabuense', 'symbol' => '$'],
        ];
    }
}

if (!function_exists('get_currency_symbol')) {
    function get_currency_symbol(string $code): string {
        static $map = null;
        if ($map === null) {
            $map = [];
            foreach (get_currency_list() as $c) {
                $map[$c['code']] = $c['symbol'] !== '' ? $c['symbol'] : $c['code'];
            }
        }
        return $map[$code] ?? $code;
    }
}
